import type { SanityOpportunityKnowledge } from "./sanityTypes"

export const SANITY_FALLBACK_KNOWLEDGE: Record<string, SanityOpportunityKnowledge> = {
  "opp-gsoc": {
    _id: "sanity-opp-gsoc",
    title: "Google Summer of Code",
    slug: { current: "google-summer-of-code" },
    organization: {
      _id: "org-google",
      name: "Google",
      slug: { current: "google" },
      website: "https://summerofcode.withgoogle.com",
      description: "Google's global open-source mentorship program connecting student developers with open-source organizations.",
      industry: "Technology / Open Source",
    },
    type: "fellowship",
    category: "Open Source Development",
    description: "Global online program focused on bringing new contributors into open source software development under 1-on-1 mentorship from experienced open source maintainers. (Note: Demo Knowledge Graph Dataset based on annual GSoC program guidelines).",
    eligibility: [
      {
        _id: "elig-gsoc-1",
        ruleType: "academic",
        description: "Must be 18 years of age or older at time of registration and enrolled in post-secondary education or a beginner open-source contributor.",
        required: true,
        degree: ["Bachelor", "Master", "PhD", "Associate"],
        year: ["Semester 1", "Semester 2", "Semester 3", "Semester 4", "Semester 5", "Semester 6", "Semester 7", "Semester 8"],
      },
      {
        _id: "elig-gsoc-2",
        ruleType: "skills",
        description: "Must demonstrate foundational version control (Git) knowledge and proficiency in at least one core programming language used by mentor organization.",
        required: true,
      },
    ],
    requiredSkills: [
      { _id: "skill-git", name: "Git", slug: { current: "git" }, category: "cloud_devops", aliases: ["GitHub", "Version Control"] },
      { _id: "skill-python", name: "Python", slug: { current: "python" }, category: "languages", aliases: ["Py"] },
      { _id: "skill-cpp", name: "C++", slug: { current: "cpp" }, category: "languages", aliases: ["CPP"] },
      { _id: "skill-java", name: "Java", slug: { current: "java" }, category: "languages" },
      { _id: "skill-go", name: "Go", slug: { current: "go" }, category: "languages", aliases: ["Golang"] },
    ],
    location: "Remote / Global",
    remote: true,
    stipendPrize: "Stipend calculated based on local purchasing power parity (PPP)",
    applicationProcess: {
      _id: "proc-gsoc",
      title: "GSoC Contributor Application Flow",
      steps: [
        "Explore participating open-source mentor organizations and review published project ideas.",
        "Join organization IRC/Discord/Slack channels and make early bugfix pull requests to prove capability.",
        "Draft a detailed technical proposal including project timeline, deliverables, and architecture.",
        "Submit proposal via official Google Summer of Code portal before deadline.",
        "Participate in Community Bonding Period upon acceptance before coding begins.",
      ],
      documents: [
        "University Proof of Enrollment or Student ID",
        "Detailed Technical Project Proposal (PDF)",
        "Resume / GitHub Portfolio",
        "Code Contribution Proof (Links to merged PRs)",
      ],
      selectionStages: [
        { stageName: "Organization Selection", description: "Google announces accepted mentor organizations." },
        { stageName: "Proposal Submission", description: "Contributors submit proposals directly to organizations." },
        { stageName: "Mentor Ranking & Selection", description: "Mentors review, interview, and rank candidate proposals." },
        { stageName: "Community Bonding", description: "Accepted contributors refine specs and set up environment." },
        { stageName: "Coding Period", description: "12 to 22 week implementation phase with midterm/final evaluations." },
      ],
      estimatedEffort: "30-40 hours total proposal & engagement effort",
    },
    resources: [
      {
        _id: "res-gsoc-1",
        title: "Official Student Contributor Guide",
        type: "handbook",
        url: "https://google.github.io/gsocguides/student/",
        description: "Comprehensive guide on communicating with mentors, writing winning proposals, and avoiding common mistakes.",
      },
      {
        _id: "res-gsoc-2",
        title: "Writing a Strong GSoC Proposal",
        type: "guide",
        url: "https://google.github.io/gsocguides/student/proposal-elements",
        description: "Template and structural breakdown for writing competitive technical project proposals.",
      },
    ],
    source: {
      _id: "src-gsoc",
      name: "Google Summer of Code Official Portal",
      url: "https://summerofcode.withgoogle.com",
      sourceType: "official_website",
      verifiedAt: "2026-09-01T00:00:00.000Z",
      notes: "Verified official Google rules and stipend structures.",
    },
    verificationState: "verified",
    lastVerifiedAt: "2026-09-01T00:00:00.000Z",
    officialUrl: "https://summerofcode.withgoogle.com",
    applicationUrl: "https://summerofcode.withgoogle.com/get-started",
    knowledgeBaseNotes: "High-prestige open source fellowship program. Demo knowledge graph record used for vertical slice testing.",
    isFallback: true,
  },
  "opp-mlh": {
    _id: "sanity-opp-mlh",
    title: "MLH Fellowship",
    slug: { current: "mlh-fellowship" },
    organization: {
      _id: "org-mlh",
      name: "Major League Hacking",
      slug: { current: "major-league-hacking" },
      website: "https://fellowship.mlh.io",
      description: "Official student hackathon league providing remote technical fellowships and open-source internships.",
      industry: "Education / Software Development",
    },
    type: "fellowship",
    category: "Software Engineering",
    description: "A 12-week internship alternative where developers contribute to real-world open source projects used by millions.",
    eligibility: [
      {
        _id: "elig-mlh-1",
        ruleType: "academic",
        description: "Open to students and recent graduates worldwide.",
        required: true,
      },
      {
        _id: "elig-mlh-2",
        ruleType: "skills",
        description: "Must be available 30-40 hours per week during the 12-week batch.",
        required: true,
      },
    ],
    requiredSkills: [
      { _id: "skill-git", name: "Git", slug: { current: "git" }, category: "cloud_devops" },
      { _id: "skill-js", name: "JavaScript", slug: { current: "javascript" }, category: "frontend" },
      { _id: "skill-python", name: "Python", slug: { current: "python" }, category: "languages" },
      { _id: "skill-react", name: "React", slug: { current: "react" }, category: "frontend" },
      { _id: "skill-nodejs", name: "Node.js", slug: { current: "nodejs" }, category: "backend" },
    ],
    location: "Remote",
    remote: true,
    stipendPrize: "Need-based educational stipend provided based on country residency",
    applicationProcess: {
      _id: "proc-mlh",
      title: "MLH Fellowship Application & Interview Pipeline",
      steps: [
        "Submit online application form with code sample link.",
        "Complete 15-minute Initial Behavioral & Eligibility Interview.",
        "Complete 30-minute Technical Code Review Interview walking through submitted code sample.",
        "Match with Pod mentor and project partner.",
      ],
      documents: ["GitHub Repository URL (Code Sample)", "Resume", "Short Essays"],
      selectionStages: [
        { stageName: "Application Screening", description: "Review of code sample quality and essay responses." },
        { stageName: "Initial Interview", description: "Verify availability, communication skills, and eligibility." },
        { stageName: "Technical Interview", description: "Deep dive into candidate's submitted code architecture." },
        { stageName: "Matching & Acceptance", description: "Pod placement based on tech stack interest." },
      ],
      estimatedEffort: "5-8 hours total application & interview process",
    },
    resources: [
      {
        _id: "res-mlh-1",
        title: "MLH Fellowship Application Guide",
        type: "guide",
        url: "https://fellowship.mlh.io/programs/software-engineering",
        description: "Overview of software engineering track expectations and code sample guidelines.",
      },
    ],
    source: {
      _id: "src-mlh",
      name: "Major League Hacking Official Site",
      url: "https://fellowship.mlh.io",
      sourceType: "official_website",
      verifiedAt: "2026-09-10T00:00:00.000Z",
    },
    verificationState: "verified",
    lastVerifiedAt: "2026-09-10T00:00:00.000Z",
    officialUrl: "https://fellowship.mlh.io",
    applicationUrl: "https://fellowship.mlh.io/apply",
    isFallback: true,
  },
  "opp-imagine-cup": {
    _id: "sanity-opp-imagine-cup",
    title: "Microsoft Imagine Cup",
    slug: { current: "microsoft-imagine-cup" },
    organization: {
      _id: "org-microsoft",
      name: "Microsoft",
      slug: { current: "microsoft" },
      website: "https://imaginecup.microsoft.com",
      description: "Global technology enterprise inspiring student innovation.",
      industry: "Technology / Cloud / AI",
    },
    type: "competition",
    category: "AI & Cloud Innovation",
    description: "Global student technology competition inviting teams to build innovative solutions utilizing Microsoft AI and Azure services.",
    eligibility: [
      {
        _id: "elig-imagine-1",
        ruleType: "academic",
        description: "Must be an actively enrolled student age 18 or older.",
        required: true,
      },
      {
        _id: "elig-imagine-2",
        ruleType: "general",
        description: "Teams of up to 4 members using Azure cloud services.",
        required: true,
      },
    ],
    requiredSkills: [
      { _id: "skill-azure", name: "Azure", slug: { current: "azure" }, category: "cloud_devops" },
      { _id: "skill-aiml", name: "AI/ML", slug: { current: "ai-ml" }, category: "ai_ml" },
      { _id: "skill-ts", name: "TypeScript", slug: { current: "typescript" }, category: "languages" },
      { _id: "skill-python", name: "Python", slug: { current: "python" }, category: "languages" },
      { _id: "skill-cloud", name: "Cloud Architecture", slug: { current: "cloud-architecture" }, category: "cloud_devops" },
    ],
    location: "Remote / Global",
    remote: true,
    stipendPrize: "$100,000 USD + Mentorship with Microsoft CEO Satya Nadella",
    applicationProcess: {
      _id: "proc-imagine",
      title: "Imagine Cup Competition Flow",
      steps: [
        "Form a team of 1 to 4 students and register on Microsoft Imagine Cup portal.",
        "Build a working MVP utilizing Azure AI services.",
        "Submit 3-minute pitch video, deck, and GitHub repository.",
        "Advance through Regional Online Semi-Finals to World Championship.",
      ],
      documents: ["Project Proposal Deck (PDF)", "3-Minute Video Demo Link", "Software Architecture Overview"],
      selectionStages: [
        { stageName: "Idea & Pitch Submission", description: "Submission of pitch video and architecture outline." },
        { stageName: "Regional Semifinals", description: "Live presentation to Microsoft technical judges." },
        { stageName: "World Finals", description: "Top global teams compete live for grand prize." },
      ],
      estimatedEffort: "40-60 hours project development",
    },
    resources: [
      {
        _id: "res-imagine-1",
        title: "Microsoft Azure Student Credit Activation",
        type: "guide",
        url: "https://azure.microsoft.com/en-us/free/students/",
        description: "$100 free Azure credits for verified student accounts.",
      },
    ],
    source: {
      _id: "src-microsoft",
      name: "Microsoft Imagine Cup Portal",
      url: "https://imaginecup.microsoft.com",
      sourceType: "official_website",
      verifiedAt: "2026-08-15T00:00:00.000Z",
    },
    verificationState: "verified",
    lastVerifiedAt: "2026-08-15T00:00:00.000Z",
    officialUrl: "https://imaginecup.microsoft.com",
    applicationUrl: "https://imaginecup.microsoft.com/register",
    isFallback: true,
  },
  "opp-gdsc-solution": {
    _id: "sanity-opp-gdsc",
    title: "Google Solution Challenge",
    slug: { current: "google-solution-challenge" },
    organization: {
      _id: "org-gdsc",
      name: "Google Developer Student Clubs",
      slug: { current: "gdsc" },
      website: "https://developers.google.com/community/gdsc-solution-challenge",
      description: "University-based community groups for students interested in Google developer technologies.",
      industry: "Education / Developer Community",
    },
    type: "competition",
    category: "Social Impact Tech",
    description: "Annual global competition inviting students to build solutions for UN 17 Sustainable Development Goals using Google technologies.",
    eligibility: [
      {
        _id: "elig-gdsc-1",
        ruleType: "affiliation",
        description: "At least one member of team must be a member of a Google Developer Student Club (GDSC) at a university.",
        required: true,
      },
    ],
    requiredSkills: [
      { _id: "skill-flutter", name: "Flutter", slug: { current: "flutter" }, category: "mobile" },
      { _id: "skill-firebase", name: "Firebase", slug: { current: "firebase" }, category: "backend" },
      { _id: "skill-gcp", name: "Google Cloud", slug: { current: "google-cloud" }, category: "cloud_devops" },
      { _id: "skill-tf", name: "TensorFlow", slug: { current: "tensorflow" }, category: "ai_ml" },
      { _id: "skill-android", name: "Android", slug: { current: "android" }, category: "mobile" },
    ],
    location: "Remote",
    remote: true,
    stipendPrize: "Top 3 winning teams receive $3,000 USD/member + Google Mentorship",
    applicationProcess: {
      _id: "proc-gdsc",
      title: "GDSC Solution Challenge Submission",
      steps: [
        "Join local university GDSC chapter.",
        "Form a team of up to 4 students.",
        "Identify a UN Sustainable Development Goal problem.",
        "Build prototype using Google Cloud / Flutter / Firebase.",
        "Submit video demo and public GitHub link.",
      ],
      documents: ["YouTube Demo Video Link", "GitHub Repository", "UN SDG Impact Report"],
      selectionStages: [
        { stageName: "Top 100 Selection", description: "Top 100 teams receive mentoring from Google engineers." },
        { stageName: "Top 10 Finalists", description: "Finalist live demo showcase." },
      ],
      estimatedEffort: "30-50 hours project development",
    },
    resources: [
      {
        _id: "res-gdsc-1",
        title: "UN 17 Sustainable Development Goals Overview",
        type: "guide",
        url: "https://sdgs.un.org/goals",
        description: "Official UN SDG goals documentation.",
      },
    ],
    source: {
      _id: "src-gdsc",
      name: "Google Developer Student Clubs",
      url: "https://developers.google.com/community/gdsc-solution-challenge",
      sourceType: "official_website",
      verifiedAt: "2026-09-05T00:00:00.000Z",
    },
    verificationState: "verified",
    lastVerifiedAt: "2026-09-05T00:00:00.000Z",
    officialUrl: "https://developers.google.com/community/gdsc-solution-challenge",
    isFallback: true,
  },
}
