import { useCallback, useEffect, useState } from "react"
import { Archive, BrainCircuit, CheckCircle2, Clock3, Loader2, Pencil, RotateCcw, Save, Trash2, UserRound } from "lucide-react"
import { useAuth } from "@/auth/auth-provider"
import { memoryService } from "@/lib/memory/memoryService"
import { plannerHistoryService } from "@/lib/memory/plannerHistoryService"
import { preferenceLearningService } from "@/lib/memory/preferenceLearningService"
import { profileService } from "@/lib/memory/profileService"
import type { LearnedPreference, MemoryEntry, MemoryProfile, PlannerHistoryItem } from "@/lib/memory/types"
import { supabase, supabaseConfigError } from "@/lib/supabase"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Input } from "@/components/ui/input"

type ProfileDraft = Omit<MemoryProfile, "user_id" | "updated_at">
const emptyProfile: ProfileDraft = { semester: null, degree: null, university: null, skills: [], interests: [], preferred_learning_style: null, preferred_study_hours: null, placement_goals: [], internship_goals: [], hackathon_interests: [], career_aspirations: null }
const list = (value: string) => value.split(",").map((item) => item.trim()).filter(Boolean)
const join = (value: string[]) => value.join(", ")

export function MemoryPage() {
  const { user } = useAuth()
  const [profile, setProfile] = useState<ProfileDraft>(emptyProfile); const [entries, setEntries] = useState<MemoryEntry[]>([]); const [preferences, setPreferences] = useState<LearnedPreference[]>([]); const [plans, setPlans] = useState<PlannerHistoryItem[]>([]); const [goals, setGoals] = useState<{ id: string; title: string; progress: number; status: string }[]>([])
  const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null); const [editing, setEditing] = useState<string | null>(null); const [draftSummary, setDraftSummary] = useState("")
  const load = useCallback(async () => { if (!user || !supabase) { setError(supabaseConfigError ?? "Your session is unavailable."); return }; const [nextProfile, nextEntries, nextPreferences, nextPlans, nextGoals] = await Promise.all([profileService.get(user.id), memoryService.list(user.id, { limit: 30 }), preferenceLearningService.list(user.id), plannerHistoryService.list(user.id, 8), supabase.from("goals").select("id,title,progress,status").eq("user_id", user.id).in("status", ["active", "paused"]).order("updated_at", { ascending: false }).limit(8)]); setProfile(nextProfile ? { ...nextProfile, user_id: undefined, updated_at: undefined } as ProfileDraft : emptyProfile); setEntries(nextEntries); setPreferences(nextPreferences); setPlans(nextPlans); if (nextGoals.error) setError(nextGoals.error.message); else setGoals(nextGoals.data ?? []) }, [user])
  useEffect(() => { const timer = window.setTimeout(() => { void load().catch((caught) => setError(caught instanceof Error ? caught.message : "Could not load AI memory.")) }, 0); return () => window.clearTimeout(timer) }, [load])
  async function saveProfile() { if (!user) return; setSaving(true); setError(null); try { await profileService.save(user.id, profile); setMessage("Personalization profile saved.") } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not save profile.") } finally { setSaving(false) } }
  async function saveEntry(entry: MemoryEntry) { if (!user || !draftSummary.trim()) return; try { await memoryService.update(entry.id, user.id, { summary: draftSummary.trim() }); setEditing(null); await load() } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not update memory.") } }
  async function manageEntry(entry: MemoryEntry, action: "archive" | "remove") { if (!user) return; try { if (action === "archive") await memoryService.archive(entry.id, user.id); else await memoryService.remove(entry.id, user.id); await load() } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not update memory.") } }
  async function reset() { if (!user || !window.confirm("Reset AI memory? Your goals, tasks, and plans will remain, but learned profile, preferences, and saved conversation memory will be removed.")) return; try { await memoryService.reset(user.id); setMessage("AI memory has been reset."); await load() } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not reset AI memory.") } }
  const field = (label: string, key: keyof ProfileDraft, placeholder: string, isList = false) => <label className="block text-sm font-medium">{label}<Input className="mt-2" placeholder={placeholder} value={isList ? join(profile[key] as string[]) : (profile[key] as string | null) ?? ""} onChange={(event) => setProfile({ ...profile, [key]: isList ? list(event.target.value) : event.target.value || null })} /></label>
  return <section className="mx-auto max-w-7xl space-y-6 pb-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium uppercase tracking-[.25em] text-primary">Personalization</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Your AI memory, visible and in your control.</h1><p className="mt-2 max-w-3xl text-muted-foreground">StudentOS uses only the memories below to tailor future plans. Archive or remove anything at any time.</p></div><Button className="border border-red-400/30 bg-red-400/10 text-red-200 hover:bg-red-400/20" onClick={() => void reset()}><RotateCcw className="size-4" />Reset AI memory</Button></div>{error && <p role="alert" className="rounded-xl border border-red-400/30 bg-red-400/10 p-3 text-sm text-red-200">{error}</p>}{message && <p className="rounded-xl border border-primary/30 bg-primary/10 p-3 text-sm text-primary">{message}</p>}
    <div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><Card><CardContent className="p-5 sm:p-6"><div className="flex items-center justify-between"><SectionTitle icon={<UserRound />} title="User profile" description="Core facts used for personalized planning." /><Button onClick={() => void saveProfile()} disabled={saving}>{saving ? <Loader2 className="size-4 animate-spin" /> : <Save className="size-4" />}Save</Button></div><div className="mt-5 grid gap-4 sm:grid-cols-2">{field("Semester", "semester", "e.g. Semester 6")}{field("Degree", "degree", "e.g. B.Tech Computer Science")}{field("University", "university", "Your university")}{field("Learning style", "preferred_learning_style", "e.g. Active recall")}{field("Preferred study hours", "preferred_study_hours", "e.g. Weekdays, 7–9 PM")}{field("Career aspirations", "career_aspirations", "e.g. Product engineer")}{field("Skills", "skills", "React, Python, SQL", true)}{field("Interests", "interests", "AI, systems design", true)}{field("Placement goals", "placement_goals", "Product companies", true)}{field("Internship goals", "internship_goals", "Frontend internship", true)}{field("Hackathon interests", "hackathon_interests", "EdTech, accessibility", true)}</div></CardContent></Card><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-1"><Metric icon={<CheckCircle2 />} label="Active goals" value={goals.length} /><Metric icon={<BrainCircuit />} label="Learned preferences" value={preferences.length} /><Metric icon={<Clock3 />} label="Plans remembered" value={plans.length} /></div></div>
    <div className="grid gap-6 xl:grid-cols-2"><Card><CardContent className="p-5"><SectionTitle icon={<CheckCircle2 />} title="Active goals" description="Goals are automatically included in future planning." /><div className="mt-4 space-y-2">{goals.map((goal) => <div key={goal.id} className="rounded-xl border border-border bg-muted/15 p-3"><div className="flex justify-between gap-3"><span className="font-medium">{goal.title}</span><Badge>{goal.status}</Badge></div><p className="mt-2 text-xs text-muted-foreground">{goal.progress}% complete</p></div>)}{!goals.length && <Empty text="No active goals yet." />}</div></CardContent></Card><Card><CardContent className="p-5"><SectionTitle icon={<BrainCircuit />} title="Learned preferences" description="Inferred from completed work and planning behavior." /><div className="mt-4 space-y-2">{preferences.map((preference) => <div key={preference.id} className="rounded-xl border border-border bg-muted/15 p-3"><div className="flex items-center justify-between gap-3"><p className="font-medium">{preference.preference_key.replaceAll("_", " ")}</p><Badge>{Math.round(preference.confidence * 100)}% confidence</Badge></div><p className="mt-1 break-words text-sm text-muted-foreground">{typeof preference.preference_value === "object" ? JSON.stringify(preference.preference_value) : String(preference.preference_value)}</p></div>)}{!preferences.length && <Empty text="Preferences will appear as you complete tasks." />}</div></CardContent></Card></div>
    <div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><Card><CardContent className="p-5"><SectionTitle icon={<Clock3 />} title="AI memory timeline" description="Meaningful summaries retained for future conversations." /><div className="mt-4 space-y-3">{entries.map((entry) => <div key={entry.id} className="rounded-xl border border-border bg-muted/10 p-4"><div className="flex gap-3"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><Badge className="capitalize">{entry.memory_type}</Badge><span className="text-xs text-muted-foreground">{new Date(entry.updated_at).toLocaleDateString()}</span></div>{editing === entry.id ? <div className="mt-3 flex gap-2"><Input value={draftSummary} onChange={(event) => setDraftSummary(event.target.value)} /><Button size="sm" onClick={() => void saveEntry(entry)}>Save</Button></div> : <p className="mt-2 text-sm leading-6">{entry.summary}</p>}</div><div className="flex h-fit gap-1"><Button size="sm" variant="ghost" aria-label="Edit memory" onClick={() => { setEditing(entry.id); setDraftSummary(entry.summary) }}><Pencil className="size-4" /></Button><Button size="sm" variant="ghost" aria-label="Archive memory" onClick={() => void manageEntry(entry, "archive")}><Archive className="size-4" /></Button><Button size="sm" variant="ghost" aria-label="Delete memory" onClick={() => void manageEntry(entry, "remove")}><Trash2 className="size-4 text-red-300" /></Button></div></div></div>)}{!entries.length && <Empty text="No meaningful conversation memories have been saved yet." />}</div></CardContent></Card><Card><CardContent className="p-5"><SectionTitle icon={<Clock3 />} title="Planner history" description="Previous execution plans inform future recommendations." /><div className="mt-4 space-y-2">{plans.map((plan) => <div key={plan.id} className="rounded-xl border border-border bg-muted/15 p-3"><p className="font-medium">{plan.title}</p><p className="mt-1 line-clamp-2 text-sm text-muted-foreground">{plan.goal}</p><p className="mt-2 text-xs text-muted-foreground">{new Date(plan.created_at).toLocaleDateString()}</p></div>)}{!plans.length && <Empty text="Your generated plans will appear here." />}</div></CardContent></Card></div>
  </section>
}

function SectionTitle({ icon, title, description }: { icon: React.ReactNode; title: string; description: string }) { return <div className="flex gap-3"><span className="mt-0.5 text-primary [&>svg]:size-5">{icon}</span><div><h2 className="font-semibold">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{description}</p></div></div> }
function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: number }) { return <Card><CardContent className="flex items-center gap-3 p-5"><span className="text-primary [&>svg]:size-5">{icon}</span><div><p className="text-2xl font-semibold">{value}</p><p className="text-sm text-muted-foreground">{label}</p></div></CardContent></Card> }
function Empty({ text }: { text: string }) { return <p className="rounded-xl border border-dashed p-4 text-sm text-muted-foreground">{text}</p> }
