import { useCallback, useEffect, useState, type ComponentType } from "react"
import { motion } from "framer-motion"
import { BrainCircuit, CalendarDays, Flame, Loader2, RefreshCw, Sparkles, Target, TrendingUp } from "lucide-react"
import { useAuth } from "@/auth/auth-provider"
import { analyticsService } from "@/lib/adaptive/analyticsService"
import { reflectionService } from "@/lib/adaptive/reflectionService"
import { habitLearningService } from "@/lib/adaptive/habitLearningService"
import { adaptivePlanner } from "@/lib/adaptive/adaptivePlanner"
import { coachingService } from "@/lib/adaptive/coachingService"
import { predictionService } from "@/lib/adaptive/predictionService"
import type { LearningSnapshot } from "@/lib/adaptive/types"
import { supabase } from "@/lib/supabase"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"

const blank: LearningSnapshot = { reflection: null, report: null, habits: [], recommendations: [], coaching: null, predictions: [], timeline: [] }
const metricCards: { title: string; key: "productivityScore" | "consistencyScore" | "focusScore" | "estimatedStudyHours"; icon: ComponentType<{ className?: string }> }[] = [{ title: "Productivity", key: "productivityScore", icon: TrendingUp }, { title: "Consistency", key: "consistencyScore", icon: CalendarDays }, { title: "Focus", key: "focusScore", icon: Target }, { title: "Study hours", key: "estimatedStudyHours", icon: Flame }]
const label = (key: string) => key.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase())
const insightValue = (value: unknown) => { if (!value || typeof value !== "object") return "Learning from your activity"; const record = value as Record<string, unknown>; return Object.entries(record).map(([key, item]) => `${label(key)}: ${Array.isArray(item) ? item.join(", ") : item ?? "Not enough evidence"}`).join(" · ") }

export function ReflectionPage() {
  const { user } = useAuth(); const [data, setData] = useState(blank); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null)
  const load = useCallback(async (refresh = false) => { if (!user || !supabase) { setLoading(false); return }; setLoading(true); setError(null); try { const reflection = refresh ? await reflectionService.generate(user.id) : await reflectionService.latest(user.id) ?? await reflectionService.generate(user.id); const habits = await habitLearningService.learnFromTasks(user.id); const report = refresh ? await analyticsService.generateMonthlyReport(user.id) : await analyticsService.latestReport(user.id) ?? await analyticsService.generateMonthlyReport(user.id); const coaching = refresh ? await coachingService.generate(user.id, reflection.metrics) : await coachingService.latest(user.id) ?? await coachingService.generate(user.id, reflection.metrics); const predictions = refresh ? await predictionService.generate(user.id, reflection.metrics.productivityScore, reflection.metrics.consistencyScore) : await predictionService.latest(user.id); const recommendations = refresh ? await adaptivePlanner.generate(user.id, habits) : await adaptivePlanner.active(user.id); const { data: timeline, error: timelineError } = await supabase.from("reflection_timeline_events").select("*").eq("user_id", user.id).order("occurred_at", { ascending: false }).limit(12); if (timelineError) throw timelineError; setData({ reflection, report, habits, coaching, predictions, recommendations, timeline: timeline ?? [] }) } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not generate your learning review.") } finally { setLoading(false) } }, [user])
  useEffect(() => { const timer = window.setTimeout(() => { void load() }, 0); return () => window.clearTimeout(timer) }, [load])
  if (loading && !data.reflection) return <div className="flex min-h-[50vh] items-center justify-center gap-3 text-muted-foreground"><Loader2 className="size-5 animate-spin text-primary" />Building your adaptive learning profile…</div>
  return <section className="mx-auto max-w-7xl space-y-6 pb-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><Badge className="bg-primary/15 text-primary"><BrainCircuit className="mr-1 size-3" />Reflection intelligence</Badge><h1 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Your progress, understood.</h1><p className="mt-2 text-muted-foreground">Evidence-based reflection, coaching, and planning adjustments.</p></div><Button onClick={() => void load(true)} disabled={loading}>{loading ? <Loader2 className="size-4 animate-spin" /> : <RefreshCw className="size-4" />}Refresh insights</Button></div>{error && <p role="alert" className="rounded-xl border border-red-400/30 bg-red-400/10 p-3 text-sm text-red-200">{error}</p>}
    {data.reflection && <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metricCards.map(({ title, key, icon: Icon }) => <Card key={title} className="bg-card/75"><CardContent className="p-5"><Icon className="size-4 text-primary" /><p className="mt-5 text-2xl font-semibold">{data.reflection!.metrics[key]}{title === "Study hours" ? "h" : "%"}</p><p className="mt-1 text-sm text-muted-foreground">{title}</p></CardContent></Card>)}</motion.div>}
    <div className="grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><Panel title="Weekly reflection" icon={<CalendarDays />}>{data.reflection ? <><div className="grid grid-cols-2 gap-3 text-sm"><Stat label="Goals completed" value={data.reflection.metrics.goalsCompleted} /><Stat label="Goals missed" value={data.reflection.metrics.goalsMissed} /><Stat label="Tasks completed" value={data.reflection.metrics.tasksCompleted} /><Stat label="Tasks skipped" value={data.reflection.metrics.tasksSkipped} /></div><div className="mt-4 space-y-2">{data.reflection.insights.map((insight) => <p key={insight} className="rounded-xl bg-primary/5 p-3 text-sm leading-6">{insight}</p>)}</div></> : <Empty text="Complete tasks to unlock your first reflection." />}</Panel><Panel title="AI coach" icon={<Sparkles />}>{data.coaching ? <div className="rounded-2xl border border-primary/20 bg-primary/5 p-4"><p className="font-medium">{data.coaching.message}</p><p className="mt-3 text-sm leading-6 text-muted-foreground"><span className="font-medium text-primary">Why this recommendation: </span>{data.coaching.rationale}</p></div> : <Empty text="Your coach will respond once there is enough activity." />}</Panel></div>
    <div className="grid gap-6 xl:grid-cols-2"><Panel title="Upcoming priorities" icon={<Target />}>{data.recommendations.length ? data.recommendations.map((item) => <div key={item.id} className="rounded-xl border border-border/70 p-3"><p className="text-sm font-medium">{item.title}</p><p className="mt-1 text-xs leading-5 text-muted-foreground"><span className="text-primary">Why: </span>{item.rationale}</p></div>) : <Empty text="Recommendations will appear as your work patterns emerge." />}</Panel><Panel title="Predictive intelligence" icon={<TrendingUp />}>{data.predictions.length ? data.predictions.map((item) => <div key={item.id} className="rounded-xl border border-border/70 p-3"><div className="flex justify-between gap-3"><p className="text-sm font-medium">{item.label}</p><span className="text-primary">{Math.round(item.score)}%</span></div><p className="mt-1 text-xs leading-5 text-muted-foreground">Why: {item.explanation}</p></div>) : <Empty text="Predictions require completed activity." />}</Panel></div>
    <div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><Panel title="Monthly performance" icon={<TrendingUp />}>{data.report ? <><div className="flex h-28 items-end gap-1.5">{data.report.report.dailyProductivity.map((item) => <div key={item.date} title={`${item.date}: ${item.score}%`} className="flex-1 rounded-t bg-primary/70" style={{ height: `${Math.max(6, item.score)}%` }} />)}</div><p className="mt-3 text-xs text-muted-foreground">Daily productivity heatmap · strongest days: {data.report.report.mostProductiveDays.join(", ") || "Not enough activity"} · weakest: {data.report.report.weakestDays.join(", ") || "Not enough activity"}</p><div className="mt-4 flex flex-wrap gap-2"><Badge className="bg-muted text-muted-foreground">{data.report.report.learningStreak} day streak</Badge><Badge className="bg-muted text-muted-foreground">Career progress {data.report.report.careerProgress}%</Badge>{data.report.report.skillGrowth.map((skill) => <Badge key={skill.skill} className="bg-muted text-muted-foreground">{skill.skill} {skill.progress}%</Badge>)}</div></> : <Empty text="Your monthly report will appear here." />}</Panel><Panel title="Personal insights" icon={<BrainCircuit />}>{data.habits.length ? data.habits.map((habit) => <div key={habit.id} className="rounded-xl border border-border/70 p-3"><p className="text-sm font-medium">{label(habit.insight_key)}</p><p className="mt-1 text-xs text-muted-foreground">{insightValue(habit.insight_value)} · {Math.round(habit.confidence * 100)}% confidence</p></div>) : <Empty text="Your habits will be learned from completed work." />}</Panel></div>
    <Panel title="Reflection timeline" icon={<CalendarDays />}>{data.timeline.length ? data.timeline.map((event) => <div key={event.id} className="flex gap-3 border-l border-primary/30 pl-4"><span className="-ml-[21px] mt-1.5 size-2.5 rounded-full bg-primary" /><div className="pb-4"><p className="text-sm font-medium">{event.title}</p><p className="text-xs text-muted-foreground">{event.description} · {new Date(event.occurred_at).toLocaleDateString()}</p></div></div>) : <Empty text="Reflections, achievements, and milestones will build a timeline here." />}</Panel>
  </section>
}
function Panel({ title, icon, children }: { title: string; icon: React.ReactNode; children: React.ReactNode }) { return <Card className="bg-card/75"><CardContent className="p-5"><h2 className="mb-4 flex items-center gap-2 font-semibold [&>svg]:size-4 [&>svg]:text-primary">{icon}{title}</h2><div className="space-y-2">{children}</div></CardContent></Card> }
function Stat({ label, value }: { label: string; value: number }) { return <div className="rounded-xl bg-muted/40 p-3"><p className="text-xl font-semibold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div> }
function Empty({ text }: { text: string }) { return <p className="rounded-xl border border-dashed border-border p-4 text-sm text-muted-foreground">{text}</p> }
