import { CheckCircle2, Clock3, FileClock, Goal, ListTodo, Sparkles, Target } from "lucide-react"
import { Link } from "react-router-dom"
import { useDashboardData } from "@/hooks/use-dashboard-data"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"

const dateFormat = new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric" })
const relative = (value: string) => { const days = Math.ceil((new Date(value).getTime() - Date.now()) / 86400000); return days <= 0 ? "Today" : days === 1 ? "Tomorrow" : `In ${days} days` }

export function DashboardPage() {
  const { tasks, goals, deadlines, runs, recommendations, activity, loading, error } = useDashboardData()
  const completed = activity.filter((item) => item.event_type === "task_completed").length
  const score = Math.min(100, Math.round((completed * 12) + (tasks.length ? 40 : 0) + (goals.length ? 20 : 0)))
  return <section className="mx-auto max-w-7xl space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium uppercase tracking-[.25em] text-primary">Command center</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Make today count.</h1><p className="mt-2 text-muted-foreground">Your live execution view, synced from your workspace.</p></div><Button asChild><Link to="/app/planner"><Sparkles className="size-4" />Open Planner</Link></Button></div>
    {error && <p role="alert" className="rounded-xl border border-red-400/30 bg-red-400/10 p-3 text-sm text-red-200">Couldn’t load workspace data: {error}</p>}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<ListTodo />} label="Today’s tasks" value={loading ? "–" : tasks.length} detail="Still to complete" /><Metric icon={<Goal />} label="Active goals" value={loading ? "–" : goals.length} detail="In progress" /><Metric icon={<FileClock />} label="Upcoming deadlines" value={loading ? "–" : deadlines.length} detail="On your horizon" /><Metric icon={<Target />} label="Productivity score" value={loading ? "–" : `${score}%`} detail="Based on workspace activity" /></div>
    <div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><Panel title="Today’s tasks" icon={<ListTodo />} action="Tasks" href="/app/tasks">{tasks.length ? tasks.map((task) => <div key={task.id} className="flex items-center gap-3 rounded-xl border border-border/70 bg-muted/15 p-3"><span className={`size-2 rounded-full ${task.priority === "High" ? "bg-rose-400" : task.priority === "Medium" ? "bg-amber-300" : "bg-sky-400"}`} /><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{task.title}</p><p className="text-xs text-muted-foreground">{task.estimated_hours ? `${task.estimated_hours}h · ` : ""}{task.priority} priority</p></div><CheckCircle2 className="size-4 text-muted-foreground" /></div>) : <Empty text="No tasks due today. Use the Planner to shape your next move." />}</Panel><Panel title="Deadlines" icon={<Clock3 />}>{deadlines.length ? deadlines.map((deadline) => <div key={deadline.id} className="flex items-center gap-3 rounded-xl border border-border/70 bg-muted/15 p-3"><div className="rounded-lg bg-primary/15 px-2 py-1 text-center text-xs font-semibold text-primary">{dateFormat.format(new Date(deadline.due_at))}</div><div className="min-w-0"><p className="truncate text-sm font-medium">{deadline.title}</p><p className="text-xs text-muted-foreground">{deadline.category} · {relative(deadline.due_at)}</p></div></div>) : <Empty text="No upcoming deadlines saved." />}</Panel></div>
    <div className="grid gap-6 xl:grid-cols-3"><Panel title="Goals" icon={<Goal />} action="Goals" href="/app/goals">{goals.length ? goals.map((goal) => <div key={goal.id} className="rounded-xl border border-border/70 bg-muted/15 p-3"><div className="flex justify-between gap-3"><p className="text-sm font-medium">{goal.title}</p><span className="text-xs text-primary">{goal.progress}%</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${goal.progress}%` }} /></div><p className="mt-2 text-xs text-muted-foreground">{goal.category}{goal.target_date ? ` · due ${dateFormat.format(new Date(goal.target_date))}` : ""}</p></div>) : <Empty text="Your active goals will appear here." />}</Panel><Panel title="Planner history" icon={<Sparkles />} action="Planner" href="/app/planner">{runs.length ? runs.map((run) => <div key={run.id} className="rounded-xl border border-border/70 bg-muted/15 p-3"><p className="text-sm font-medium">{run.title}</p><p className="mt-1 text-xs text-muted-foreground">{run.goal_type} · {dateFormat.format(new Date(run.created_at))}</p></div>) : <Empty text="Generated plans are saved here." />}</Panel><Panel title="AI recommendations" icon={<Sparkles />}>{recommendations.length ? recommendations.map((item) => <div key={item.id} className="rounded-xl border border-primary/20 bg-primary/5 p-3"><p className="text-sm leading-5 text-foreground">{item.content}</p><p className="mt-2 text-xs text-primary">{item.source}</p></div>) : <Empty text="Your Planner recommendations will appear here." />}</Panel></div>
    <Panel title="Recent activity" icon={<Clock3 />}>{activity.length ? activity.map((item) => <div key={item.id} className="flex gap-3 border-b border-border/70 py-3 last:border-0"><span className="mt-1.5 size-2 rounded-full bg-primary" /><div><p className="text-sm">{item.description}</p><p className="mt-1 text-xs text-muted-foreground">{dateFormat.format(new Date(item.created_at))}</p></div></div>) : <Empty text="Complete a task or generate a plan to begin your activity timeline." />}</Panel>
  </section>
}
function Metric({ icon, label, value, detail }: { icon: React.ReactNode; label: string; value: string | number; detail: string }) { return <Card className="border-border/80 bg-card/75"><CardContent className="p-5"><div className="flex items-center justify-between text-primary [&>svg]:size-4">{icon}<Badge className="bg-muted text-muted-foreground">Live</Badge></div><p className="mt-5 text-2xl font-semibold">{value}</p><p className="mt-1 text-sm font-medium">{label}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></CardContent></Card> }
function Panel({ title, icon, children, action, href }: { title: string; icon: React.ReactNode; children: React.ReactNode; action?: string; href?: string }) { return <Card className="border-border/80 bg-card/75"><CardContent className="p-5"><div className="mb-4 flex items-center justify-between"><h2 className="flex items-center gap-2 font-semibold text-foreground [&>svg]:size-4 [&>svg]:text-primary">{icon}{title}</h2>{action && href && <Link className="text-xs font-medium text-primary hover:underline" to={href}>{action}</Link>}</div><div className="space-y-2">{children}</div></CardContent></Card> }
function Empty({ text }: { text: string }) { return <div className="rounded-xl border border-dashed border-border bg-muted/10 p-5 text-sm leading-6 text-muted-foreground">{text}</div> }
