import { useCallback, useEffect, useState } from "react"
import { useAuth } from "@/auth/auth-provider"
import { supabase, supabaseConfigError } from "@/lib/supabase"

export type GoalStatus = "active" | "completed" | "paused"
export type TrackedGoal = { id: string; title: string; category: string; target_date: string | null; progress: number; status: GoalStatus; created_at: string }
export type Milestone = { id: string; goal_id: string; title: string; target_date: string | null; is_completed: boolean; completed_at: string | null }
export type GoalRecommendation = { id: string; content: string; created_at: string }
export type GoalInput = { title: string; category: string; targetDate: string; progress: number; status: GoalStatus }

export function useGoalTracking() {
  const { user } = useAuth()
  const [goals, setGoals] = useState<TrackedGoal[]>([]); const [milestones, setMilestones] = useState<Milestone[]>([]); const [recommendations, setRecommendations] = useState<GoalRecommendation[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null)
  const refresh = useCallback(async () => { if (!supabase || !user) { setLoading(false); if (!supabase) setError(supabaseConfigError); return }; setLoading(true); const [goalResult, milestoneResult, recResult] = await Promise.all([supabase.from("goals").select("id,title,category,target_date,progress,status,created_at").eq("user_id", user.id).order("target_date", { ascending: true, nullsFirst: false }), supabase.from("goal_milestones").select("id,goal_id,title,target_date,is_completed,completed_at").eq("user_id", user.id).order("target_date", { ascending: true, nullsFirst: false }), supabase.from("ai_recommendations").select("id,content,created_at").eq("user_id", user.id).eq("source", "Goal Agent").eq("is_dismissed", false).order("created_at", { ascending: false }).limit(8)]); const failed = goalResult.error ?? milestoneResult.error ?? recResult.error; if (failed) setError(failed.message); else { setGoals((goalResult.data ?? []) as TrackedGoal[]); setMilestones((milestoneResult.data ?? []) as Milestone[]); setRecommendations((recResult.data ?? []) as GoalRecommendation[]); setError(null) }; setLoading(false) }, [user])
  useEffect(() => { const timer = window.setTimeout(() => { void refresh() }, 0); return () => window.clearTimeout(timer) }, [refresh])
  useEffect(() => { const client = supabase; if (!client || !user) return; const channel = client.channel(`goals-${user.id}`).on("postgres_changes", { event: "*", schema: "public", table: "goals", filter: `user_id=eq.${user.id}` }, refresh).on("postgres_changes", { event: "*", schema: "public", table: "goal_milestones", filter: `user_id=eq.${user.id}` }, refresh).on("postgres_changes", { event: "*", schema: "public", table: "ai_recommendations", filter: `user_id=eq.${user.id}` }, refresh).subscribe(); return () => { void client.removeChannel(channel) } }, [refresh, user])
  async function createGoal(input: GoalInput) { if (!supabase || !user) return fail(); const { error: saveError } = await supabase.from("goals").insert({ user_id: user.id, title: input.title.trim(), category: input.category.trim() || "Personal", target_date: input.targetDate || null, progress: input.progress, status: input.status }); await handle(saveError) }
  async function updateGoal(id: string, input: GoalInput) { if (!supabase || !user) return fail(); const { error: saveError } = await supabase.from("goals").update({ title: input.title.trim(), category: input.category.trim() || "Personal", target_date: input.targetDate || null, progress: input.progress, status: input.status, updated_at: new Date().toISOString() }).eq("id", id).eq("user_id", user.id); await handle(saveError) }
  async function removeGoal(id: string) { if (!supabase || !user) return fail(); const { error: deleteError } = await supabase.from("goals").delete().eq("id", id).eq("user_id", user.id); await handle(deleteError) }
  async function addMilestone(goalId: string, title: string, targetDate: string) { if (!supabase || !user) return fail(); const { error: saveError } = await supabase.from("goal_milestones").insert({ user_id: user.id, goal_id: goalId, title: title.trim(), target_date: targetDate || null }); await handle(saveError) }
  async function toggleMilestone(milestone: Milestone) { if (!supabase || !user) return fail(); const done = !milestone.is_completed; const { error: saveError } = await supabase.from("goal_milestones").update({ is_completed: done, completed_at: done ? new Date().toISOString() : null }).eq("id", milestone.id).eq("user_id", user.id); await handle(saveError) }
  async function removeMilestone(id: string) { if (!supabase || !user) return fail(); const { error: deleteError } = await supabase.from("goal_milestones").delete().eq("id", id).eq("user_id", user.id); await handle(deleteError) }
  async function saveRecommendations(items: { priority: string; content: string }[]) { if (!supabase || !user) return fail(); const { error: saveError } = await supabase.from("ai_recommendations").insert(items.map((item) => ({ user_id: user.id, source: "Goal Agent", content: `[${item.priority}] ${item.content}` }))); await handle(saveError) }
  async function dismissRecommendation(id: string) { if (!supabase || !user) return fail(); const { error: saveError } = await supabase.from("ai_recommendations").update({ is_dismissed: true }).eq("id", id).eq("user_id", user.id); await handle(saveError) }
  async function handle(saveError: { message: string } | null) { if (saveError) setError(saveError.message); else await refresh() }
  function fail() { setError(supabaseConfigError ?? "Your session is unavailable.") }
  return { goals, milestones, recommendations, loading, error, clearError: () => setError(null), reportError: (message: string) => setError(message), createGoal, updateGoal, removeGoal, addMilestone, toggleMilestone, removeMilestone, saveRecommendations, dismissRecommendation }
}
