import { useMemo, useState, type FormEvent } from "react"
import { CalendarDays, Check, CheckCircle2, ChevronDown, Circle, Clock3, Pencil, Plus, SlidersHorizontal, Trash2, X } from "lucide-react"
import { useTasks, type ManagedTask, type TaskInput, type TaskPriority, type TaskStatus } from "@/hooks/use-tasks"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Input } from "@/components/ui/input"

const blankTask = (): TaskInput => ({ title: "", dueAt: "", priority: "Medium", estimatedHours: "", status: "todo" })
const priorities: TaskPriority[] = ["High", "Medium", "Low"]
const statuses: { value: TaskStatus | "all"; label: string }[] = [{ value: "all", label: "All" }, { value: "todo", label: "To do" }, { value: "in_progress", label: "In progress" }, { value: "completed", label: "Completed" }]
type DateFilter = "all" | "overdue" | "today" | "upcoming" | "none"

export function TasksPage() {
  const { tasks, loading, error, clearError, create, update, toggleComplete, remove } = useTasks()
  const [showCreate, setShowCreate] = useState(false)
  const [draft, setDraft] = useState<TaskInput>(blankTask)
  const [editing, setEditing] = useState<string | null>(null)
  const [statusFilter, setStatusFilter] = useState<TaskStatus | "all">("all")
  const [priorityFilter, setPriorityFilter] = useState<TaskPriority | "all">("all")
  const [dateFilter, setDateFilter] = useState<DateFilter>("all")

  const filteredTasks = useMemo(() => tasks.filter((task) => matchesFilters(task, statusFilter, priorityFilter, dateFilter)), [tasks, statusFilter, priorityFilter, dateFilter])
  const completed = tasks.filter((task) => task.status === "completed").length
  const open = tasks.length - completed

  async function submitCreate(event: FormEvent) { event.preventDefault(); if (!draft.title.trim()) return; await create(draft); setDraft(blankTask()); setShowCreate(false) }
  async function submitEdit(event: FormEvent, task: ManagedTask, input: TaskInput) { event.preventDefault(); if (!input.title.trim()) return; await update(task.id, input); setEditing(null) }

  return <section className="mx-auto max-w-6xl space-y-6 pb-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium uppercase tracking-[.25em] text-primary">Execution</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Tasks that move work forward.</h1><p className="mt-2 text-muted-foreground">Plan, prioritize, and complete work with live Supabase synchronization.</p></div><Button onClick={() => { setShowCreate(true); setEditing(null); clearError() }}><Plus className="size-4" />New task</Button></div>
    <div className="grid gap-3 sm:grid-cols-3"><Summary icon={<Circle />} label="Open" value={open} /><Summary icon={<CheckCircle2 />} label="Completed" value={completed} /><Summary icon={<Clock3 />} label="Completion" value={tasks.length ? `${Math.round((completed / tasks.length) * 100)}%` : "—"} /></div>
    {error && <p role="alert" className="rounded-xl border border-red-400/30 bg-red-400/10 p-3 text-sm text-red-200">{error}</p>}
    {showCreate && <TaskForm title="Create task" value={draft} onChange={setDraft} onSubmit={submitCreate} onCancel={() => { setShowCreate(false); setDraft(blankTask()) }} submitLabel="Create task" />}
    <Card><CardContent className="p-4 sm:p-6"><div className="mb-5 flex flex-wrap items-center gap-3"><div className="flex items-center gap-2 font-semibold"><SlidersHorizontal className="size-4 text-primary" />Filters</div><FilterSelect value={statusFilter} onChange={(value) => setStatusFilter(value as TaskStatus | "all")} options={statuses.map((item) => [item.value, item.label])} /><FilterSelect value={priorityFilter} onChange={(value) => setPriorityFilter(value as TaskPriority | "all")} options={[["all", "All priorities"], ...priorities.map((item) => [item, item])] as [string, string][]} /><FilterSelect value={dateFilter} onChange={(value) => setDateFilter(value as DateFilter)} options={[["all", "Any date"], ["overdue", "Overdue"], ["today", "Due today"], ["upcoming", "Upcoming"], ["none", "No due date"]]} /><span className="ml-auto text-sm text-muted-foreground">{filteredTasks.length} shown</span></div><div className="space-y-3">{loading && <p className="p-6 text-center text-sm text-muted-foreground">Loading tasks…</p>}{filteredTasks.map((task) => editing === task.id ? <TaskEditor key={task.id} task={task} onSubmit={submitEdit} onCancel={() => setEditing(null)} /> : <TaskRow key={task.id} task={task} onToggle={() => void toggleComplete(task)} onEdit={() => { setEditing(task.id); setShowCreate(false) }} onDelete={() => void remove(task.id)} />)}{!loading && !filteredTasks.length && <p className="rounded-2xl border border-dashed p-10 text-center text-sm text-muted-foreground">No tasks match these filters. Create one or adjust the filters to see more work.</p>}</div></CardContent></Card></section>
}

function TaskForm({ title, value, onChange, onSubmit, onCancel, submitLabel }: { title: string; value: TaskInput; onChange: (value: TaskInput) => void; onSubmit: (event: FormEvent) => void; onCancel: () => void; submitLabel: string }) { return <Card><CardContent className="p-5"><h2 className="font-semibold">{title}</h2><form className="mt-4 grid gap-4 lg:grid-cols-[minmax(0,1fr)_190px_150px_140px_auto]" onSubmit={onSubmit}><Input value={value.title} onChange={(event) => onChange({ ...value, title: event.target.value })} placeholder="What needs to be done?" autoFocus required /><label className="relative"><CalendarDays className="pointer-events-none absolute left-3 top-3.5 size-4 text-muted-foreground" /><input type="datetime-local" value={value.dueAt} onChange={(event) => onChange({ ...value, dueAt: event.target.value })} className="h-11 w-full rounded-xl border border-border bg-muted/40 pl-9 pr-2 text-sm outline-none focus:border-primary/60" aria-label="Due date" /></label><Select value={value.priority} onChange={(priority) => onChange({ ...value, priority: priority as TaskPriority })} options={priorities.map((item) => [item, item])} /><Input type="number" min="0" step="0.5" value={value.estimatedHours} onChange={(event) => onChange({ ...value, estimatedHours: event.target.value })} placeholder="Hours" aria-label="Estimated hours" /><div className="flex gap-2"><Button type="submit"><Check className="size-4" />{submitLabel}</Button><Button type="button" variant="ghost" onClick={onCancel} aria-label="Cancel"><X className="size-4" /></Button></div></form></CardContent></Card> }

function TaskEditor({ task, onSubmit, onCancel }: { task: ManagedTask; onSubmit: (event: FormEvent, task: ManagedTask, input: TaskInput) => Promise<void>; onCancel: () => void }) { const [value, setValue] = useState<TaskInput>({ title: task.title, dueAt: toDateTimeInput(task.due_at), priority: task.priority, estimatedHours: task.estimated_hours?.toString() ?? "", status: task.status }); return <div className="rounded-2xl border border-primary/30 bg-primary/5 p-4"><form onSubmit={(event) => void onSubmit(event, task, value)} className="grid gap-3 lg:grid-cols-[minmax(0,1fr)_180px_130px_130px_auto]"><Input value={value.title} onChange={(event) => setValue({ ...value, title: event.target.value })} required /><input type="datetime-local" value={value.dueAt} onChange={(event) => setValue({ ...value, dueAt: event.target.value })} className="h-11 rounded-xl border border-border bg-background px-2 text-sm" /><Select value={value.priority} onChange={(priority) => setValue({ ...value, priority: priority as TaskPriority })} options={priorities.map((item) => [item, item])} /><Select value={value.status} onChange={(status) => setValue({ ...value, status: status as TaskStatus })} options={statuses.slice(1).map((item) => [item.value, item.label])} /><div className="flex gap-2"><Button type="submit" size="sm">Save</Button><Button type="button" size="sm" variant="ghost" onClick={onCancel}>Cancel</Button></div></form></div> }

function TaskRow({ task, onToggle, onEdit, onDelete }: { task: ManagedTask; onToggle: () => void; onEdit: () => void; onDelete: () => void }) { return <div className={`flex gap-3 rounded-2xl border border-border p-4 transition ${task.status === "completed" ? "bg-muted/10 opacity-70" : "bg-muted/15"}`}><button onClick={onToggle} className="mt-0.5 rounded-full text-primary hover:text-primary/80" aria-label={task.status === "completed" ? "Mark task incomplete" : "Mark task complete"}>{task.status === "completed" ? <CheckCircle2 className="size-5" /> : <Circle className="size-5" />}</button><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className={task.status === "completed" ? "font-medium line-through" : "font-medium"}>{task.title}</p><PriorityBadge priority={task.priority} />{task.status === "in_progress" && <Badge className="bg-sky-400/15 text-sky-200">In progress</Badge>}</div><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-muted-foreground"><span className={isOverdue(task) ? "text-rose-300" : ""}>{task.due_at ? `Due ${formatDate(task.due_at)}` : "No due date"}</span>{task.estimated_hours !== null && <span>{task.estimated_hours} estimated hours</span>}{task.completed_at && <span>Completed {formatDate(task.completed_at)}</span>}</div></div><div className="flex items-start gap-1"><Button variant="ghost" size="sm" onClick={onEdit} aria-label={`Edit ${task.title}`}><Pencil className="size-4" /></Button><Button variant="ghost" size="sm" onClick={onDelete} aria-label={`Delete ${task.title}`}><Trash2 className="size-4 text-red-300" /></Button></div></div> }

function Summary({ icon, label, value }: { icon: React.ReactNode; label: string; value: string | number }) { return <Card><CardContent className="flex items-center gap-3 p-4"><span className="text-primary [&>svg]:size-5">{icon}</span><div><p className="text-xs text-muted-foreground">{label}</p><p className="text-xl font-semibold">{value}</p></div></CardContent></Card> }
function Select({ value, onChange, options }: { value: string; onChange: (value: string) => void; options: [string, string][] }) { return <div className="relative"><select value={value} onChange={(event) => onChange(event.target.value)} className="h-11 w-full appearance-none rounded-xl border border-border bg-muted/40 px-3 pr-8 text-sm outline-none focus:border-primary/60">{options.map(([optionValue, label]) => <option key={optionValue} value={optionValue}>{label}</option>)}</select><ChevronDown className="pointer-events-none absolute right-2 top-3.5 size-4 text-muted-foreground" /></div> }
function FilterSelect(props: { value: string; onChange: (value: string) => void; options: [string, string][] }) { return <Select {...props} /> }
function PriorityBadge({ priority }: { priority: TaskPriority }) { return <Badge className={priority === "High" ? "bg-rose-400/15 text-rose-200" : priority === "Medium" ? "bg-amber-400/15 text-amber-200" : "bg-muted text-muted-foreground"}>{priority}</Badge> }
function toDateTimeInput(value: string | null) { if (!value) return ""; const date = new Date(value); const offset = date.getTimezoneOffset(); return new Date(date.getTime() - offset * 60_000).toISOString().slice(0, 16) }
function formatDate(value: string) { return new Date(value).toLocaleString(undefined, { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }) }
function isOverdue(task: ManagedTask) { return task.status !== "completed" && Boolean(task.due_at && new Date(task.due_at) < new Date()) }
function matchesFilters(task: ManagedTask, status: TaskStatus | "all", priority: TaskPriority | "all", date: DateFilter) { if (status !== "all" && task.status !== status) return false; if (priority !== "all" && task.priority !== priority) return false; if (date === "all") return true; if (date === "none") return !task.due_at; if (!task.due_at) return false; const due = new Date(task.due_at); const now = new Date(); const start = new Date(now); start.setHours(0, 0, 0, 0); const tomorrow = new Date(start); tomorrow.setDate(tomorrow.getDate() + 1); if (date === "overdue") return due < start; if (date === "today") return due >= start && due < tomorrow; return due >= tomorrow }
