export const demoWorkspace = {
  profile: { name: "Aarav Mehta", university: "Indian Institute of Technology, Delhi", program: "B.Tech · Computer Science", semester: "Semester 6" },
  metrics: { productivity: 87, consistency: 82, streak: 12, goalProgress: 74, studyHours: 18.5 },
  tasks: [{ id: "d1", title: "Finish system design case study", priority: "High", estimated_hours: 2, due_at: new Date().toISOString(), status: "todo" }, { id: "d2", title: "Revise dynamic programming patterns", priority: "High", estimated_hours: 1.5, due_at: new Date().toISOString(), status: "todo" }, { id: "d3", title: "Review recruiter outreach draft", priority: "Medium", estimated_hours: 0.5, due_at: new Date().toISOString(), status: "todo" }],
  goals: [{ id: "g1", title: "Secure a frontend internship", category: "Career", progress: 76, target_date: "2026-08-30", status: "active" }, { id: "g2", title: "Master data structures", category: "Academic", progress: 68, target_date: "2026-09-12", status: "active" }, { id: "g3", title: "Ship CampusConnect MVP", category: "Project", progress: 91, target_date: "2026-08-10", status: "active" }],
  deadlines: [{ id: "dd1", title: "Atlassian internship application", category: "Career", due_at: "2026-07-22T18:00:00.000Z" }, { id: "dd2", title: "Algorithms mid-semester", category: "Academic", due_at: "2026-07-28T05:30:00.000Z" }, { id: "dd3", title: "HackIndia prototype submission", category: "Hackathon", due_at: "2026-08-03T12:00:00.000Z" }],
  recommendations: [{ id: "r1", content: "Start with the case study at 7:00 PM—your strongest completion window over the past three weeks.", source: "Adaptive Planner" }, { id: "r2", content: "Protect Friday for applications: your career tasks are completed 31% more often then.", source: "AI Coach" }, { id: "r3", content: "Split the DP revision into two 45-minute blocks to maintain your focus score.", source: "Focus Intelligence" }],
  activity: [{ id: "a1", event_type: "task_completed", description: "Completed React performance optimization lab", created_at: "2026-07-18T12:30:00.000Z" }, { id: "a2", event_type: "achievement", description: "Unlocked: 10-day learning streak", created_at: "2026-07-17T16:00:00.000Z" }, { id: "a3", event_type: "plan", description: "AI refreshed your internship roadmap", created_at: "2026-07-17T09:00:00.000Z" }],
  reflection: { id: "wr1", period_start: "2026-07-12", period_end: "2026-07-18", metrics: { goalsCompleted: 2, goalsMissed: 0, tasksCompleted: 14, tasksSkipped: 1, productivityScore: 87, consistencyScore: 82, focusScore: 79, estimatedStudyHours: 18.5 }, insights: ["Your 12-day streak is driven by short evening focus sessions.", "Career momentum is strongest on Fridays—keep applications grouped there.", "One delayed task suggests reducing Monday workload by 30 minutes."], generated_at: "2026-07-18T12:00:00.000Z" },
  chart: [55, 68, 63, 82, 76, 91, 87],
} as const
