-- ── Phase 7: Hackathon Intelligence & Multi-Source Ingestion Migration ────────
-- Migration: 20260718070000_create_hackathon_ingestion_tables.sql

-- 1. Add raw_metadata jsonb column for multi-source payload audit
alter table public.opportunities add column if not exists raw_metadata jsonb default '{}'::jsonb;

-- 2. Verified Multi-Source Hackathon Opportunities Seed Data
insert into public.opportunities (
  title, organization, type, category, description,
  eligibility, required_skills, location, stipend_prize,
  source_url, source_platform, deadline, application_open_date,
  status, verification_state, last_verified_at
) values
(
  'Global AI Hackathon 2026',
  'Devpost Community',
  'hackathon',
  'Artificial Intelligence',
  'Global online hackathon challenging developers to build innovative AI agents, multimodal pipelines, and autonomous workflows.',
  array['Open to developers worldwide age 18+'],
  array['Python', 'OpenAI', 'TypeScript', 'TensorFlow', 'React'],
  'Remote / Global',
  '$50,000 USD Total Prize Pool',
  'https://devpost.com/hackathons',
  'Devpost',
  null,
  null,
  'active',
  'verified',
  now()
),
(
  'ETHIndia Hackathon 2026',
  'Devfolio',
  'hackathon',
  'Web3 & Blockchain',
  'Asia''s largest Ethereum hackathon bringing together top Web3 builders, smart contract developers, and decentralization enthusiasts.',
  array['Open to developers and students worldwide'],
  array['Solidity', 'TypeScript', 'Ethereum', 'React', 'Smart Contracts'],
  'Bengaluru, India / Hybrid',
  '$100,000 USD Prize Pool + Builder Grants',
  'https://devfolio.co/hackathons',
  'Devfolio',
  null,
  null,
  'active',
  'verified',
  now()
),
(
  'National Student Innovation Hackathon',
  'Unstop',
  'hackathon',
  'Full Stack & Cloud',
  'Pan-India college hackathon encouraging students to solve real-world industry challenges across cloud, mobility, and AI.',
  array['Enrolled college student in India', 'Teams of 2 to 4 members'],
  array['Java', 'Python', 'React', 'Node.js', 'MongoDB'],
  'India / Hybrid',
  '₹500,000 INR Cash Prizes + PPI Opportunities',
  'https://unstop.com/hackathons',
  'Unstop',
  null,
  null,
  'active',
  'verified',
  now()
),
(
  'HackerEarth International Open Hackathon',
  'HackerEarth',
  'hackathon',
  'Algorithms & AI',
  'Global online coding challenge testing algorithmic problem solving, machine learning pipelines, and backend system scalability.',
  array['Open to all developers and university students globally'],
  array['C++', 'Python', 'Java', 'Algorithms', 'Data Structures'],
  'Remote / Global',
  '$25,000 USD Cash Prizes + Hiring Interviews',
  'https://www.hackerearth.com/challenges/',
  'HackerEarth',
  null,
  null,
  'active',
  'verified',
  now()
),
(
  'Hack2Skill Innovation Summit Hackathon',
  'Hack2Skill',
  'hackathon',
  'Developer Innovation',
  'Industry-backed innovation hackathon building prototype solutions for fintech, edtech, and sustainability.',
  array['Open to student developers and early-stage startup builders'],
  array['React', 'Node.js', 'Python', 'Cloud Computing'],
  'Remote / India',
  '₹300,000 INR Cash Pool + Incubator Credits',
  'https://hack2skill.com/hackathons',
  'Hack2Skill',
  null,
  null,
  'active',
  'verified',
  now()
),
(
  'Smart India Hackathon 2026 (SIH)',
  'Ministry of Education & AICTE',
  'hackathon',
  'National Governance & Hardware/Software Tech',
  'Nationwide initiative for Indian college students to solve pressing problem statements from government ministries, departments, and industries.',
  array['Enrolled college/university student in India', 'Official team nomination by institution'],
  array['Python', 'Java', 'IoT', 'Flutter', 'Machine Learning'],
  'India (Nodal Centers)',
  '₹100,000 INR per winning problem statement + Government Recognition',
  'https://www.sih.gov.in',
  'Smart India Hackathon',
  null,
  null,
  'active',
  'verified',
  now()
),
(
  'HackHazard Global Student Hackathon',
  'HackHazard Community',
  'hackathon',
  'Open Source Tech',
  '48-hour global virtual student hackathon focused on building open source developer tooling, security apps, and educational software.',
  array['Open to student developers worldwide'],
  array['TypeScript', 'Rust', 'Go', 'Git', 'Docker'],
  'Remote / Global',
  '$10,000 USD Swag, Hosting Credits & Sponsor Prizes',
  'https://hackhazard.dev',
  'HackHazard',
  null,
  null,
  'active',
  'verified',
  now()
)
on conflict (source_platform, source_url) do update set
  title = excluded.title,
  organization = excluded.organization,
  category = excluded.category,
  description = excluded.description,
  required_skills = excluded.required_skills,
  last_verified_at = now();
